version: '3.8'

services:
  api:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - ./db:/app/db
    environment:
      - DATABASE_URL=sqlite:///app/db/investor_commitments.db
    command: uvicorn fastapi_preqin_backend:app --host 0.0.0.0 --port 8000 --reload
